Don't use csh

diff --git a/share/javapp b/share/javapp
--- a/share/javapp
+++ b/share/javapp
@@ -1,23 +1,22 @@
-#! /bin/csh
+#! /bin/sh
 # Pretty-print a Java file, overwriting the original contents but saving the
 # original non-pretty-printed file with a ".unpp" extension.
 
-# This is a shell script rather than a shell alias like
+# This is a shell script rather than a shell alias like the csh alias
 #   alias	javapp	'mv -f \!* \!*.unpp; java JavaPP \!*.unpp > \!*'
 # so that it can take multiple arguments.
 
-while ($#argv)
-    set f = "$argv[1]"
-    set tmp = "$f.javapp.$$"
-    java -mx192m -classpath $HOME/java/JavaPrinter:$CLASSPATH JavaPP "$f" > "$tmp"
-    if ($status != 0) then
-        echo "javapp: pretty-printing failed for $f" > /dev/stderr
-        rm -f "$tmp"
-        exit 1
-    endif
-    # Keep the first ".unpp" file, which holds the original, never-pretty-printed
-    # text; a later run would otherwise overwrite it with pretty-printed text.
-    if (! -e "$f.unpp") mv -f "$f" "$f.unpp"
-    mv -f "$tmp" "$f"
-    shift
-end
+for f in "$@"; do
+  tmp="$f.javapp.$$"
+  if ! java -mx192m -classpath "$HOME/java/JavaPrinter${CLASSPATH:+:$CLASSPATH}" JavaPP "$f" > "$tmp"; then
+    echo "javapp: pretty-printing failed for $f" 1>&2
+    rm -f "$tmp"
+    exit 1
+  fi
+  # Keep the first ".unpp" file, which holds the original, never-pretty-printed
+  # text; a later run would otherwise overwrite it with pretty-printed text.
+  if [ ! -e "$f.unpp" ]; then
+    mv -f "$f" "$f.unpp"
+  fi
+  mv -f "$tmp" "$f"
+done
diff --git a/share/print-mail b/share/print-mail
--- a/share/print-mail
+++ b/share/print-mail
@@ -1,64 +1,71 @@
-#! /bin/csh
-# No -f flag to csh because I want my .cshrc read: set path, aliases.
+#!/bin/bash -l
+# The "-l" on the line above makes this a login shell, so that my startup files
+# are read: ~/.bash_profile reads ~/.profile, which sets PATH.
 # Not named "printmail" because that is part of elm.
 # Invoke like this:  "print-mail bulk" or "print-mail -o outfile.ps bulk"
 
-set valid_opts = "-[o]"
+usage() {
+  echo "Usage: $0 [-o outfile.ps] dropname       eg: $0 bulk" 1>&2
+}
 
-while ($#argv > 0)
-  if ("$1" =~ $valid_opts) then
-    unset getcommand; unset getfilterlist; unset getnamelist
-    switch ("$1")
-    case -o:
+outfile=""
+dropname=""
+
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+    -o)
       shift
-      set outfile = $1
-      breaksw
-    endsw
-  else
-    if ($?dropname) then
-      echo "Error: supplied two drop names"
-      echo "Usage: $0 [-o outfile.ps] dropname       eg: $0 bulk"
-      exit 1
-    endif
-    set dropname = $1
-  endif
+      if [ "$#" -eq 0 ]; then
+        echo "Error: -o requires an argument" 1>&2
+        usage
+        exit 1
+      fi
+      outfile="$1"
+      ;;
+    *)
+      if [ -n "$dropname" ]; then
+        echo "Error: supplied two drop names" 1>&2
+        usage
+        exit 1
+      fi
+      dropname="$1"
+      ;;
+  esac
   shift
-end
+done
 
-if (! $?dropname) then
-  echo "Error: no drop name supplied"
-  echo "Usage: $0 [-o outfile.ps] dropname       eg: $0 bulk"
+if [ -z "$dropname" ]; then
+  echo "Error: no drop name supplied" 1>&2
+  usage
   exit 1
-endif
+fi
 
-cd ~/.mail
+cd ~/.mail || exit 1
 
-if (!(-e .maildrop-$dropname)) then
-  echo "File .maildrop-$dropname does not exist"
+if [ ! -e ".maildrop-$dropname" ]; then
+  echo "File .maildrop-$dropname does not exist" 1>&2
   exit 1
-endif
+fi
 
-if (-z .maildrop-$dropname) then
-  echo "File .maildrop-$dropname is empty"
+if [ ! -s ".maildrop-$dropname" ]; then
+  echo "File .maildrop-$dropname is empty" 1>&2
   exit 1
-endif
+fi
 
 # movemail .maildrop-$dropname $dropname-mail
 # /usr/lib/emacs/21.4/i386-linux/movemail .maildrop-$dropname $dropname-mail
 # /usr/libexec/emacs/22.2/i686-pc-linux-gnu/movemail .maildrop-$dropname $dropname-mail
-movemail .maildrop-$dropname $dropname-mail
-if ($status != 0) exit
+movemail ".maildrop-$dropname" "$dropname-mail" || exit 1
 # Remove .maildrop file, which isn't used since I no longer use procmail.
-rm -f .maildrop-$dropname
-if ($status != 0) exit
-emacs -batch $dropname-mail -l ~/.emacs -l ~/emacs/mail-simplify -f clean-mail-buffer -f save-buffer >& /dev/null
-if ($?outfile) then
-  enscript --pretty-print -2r -o $outfile $dropname-mail
+rm -f ".maildrop-$dropname" || exit 1
+emacs -batch "$dropname-mail" -l ~/.emacs -l ~/emacs/mail-simplify -f clean-mail-buffer -f save-buffer > /dev/null 2>&1
+if [ -n "$outfile" ]; then
+  enscript --pretty-print -2r -o "$outfile" "$dropname-mail"
   echo "Created $outfile; consider deleting $dropname-mail-$$"
 else
-  enscript --pretty-print -2r $dropname-mail
+  enscript --pretty-print -2r "$dropname-mail"
   echo "Printed $dropname-mail; consider deleting $dropname-mail-$$"
-endif
-mv $dropname-mail.~1~ $dropname-mail-$$.~1~
-mv $dropname-mail $dropname-mail-$$
-chmod og-rw $dropname-mail-$$*
+fi
+mv "$dropname-mail.~1~" "$dropname-mail-$$.~1~"
+mv "$dropname-mail" "$dropname-mail-$$"
+chmod og-rw "$dropname-mail-$$"*
